title: kennethdait on GitHub
author: Kenneth Dait
email: kendaitdev@icloud.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is my GitHub jekyl page.
# social links
twitter_username: kenanigans # DO NOT include the @ character, or else the build will fail!
github_username:  kennethdait # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
